// src/push-setting/graph/components/boolean-edge-form/index.vue
<template>
  <a-form ref="form" :model="form" label-width="120px">
    <a-form-item label="条件是否成立">
      <a-switch v-model="form.value"></a-switch>
    </a-form-item>
  </a-form>
</template>

<script>
import { BooleanEdge } from '../../edges/boolean-edge'

export default {
  name: 'BooleanEdgeForm',
  props: {
    edge: {
      type: BooleanEdge,
      default: null
    }
  },
  data () {
    return {
      form: {
        value: this.edge.value
      }
    }
  },
  watch: {
    edge () {
      this.form.value = this.edge.value
    },
    form: {
      handler () {
        this.edge.changeValue(this.form.value)
      },
      deep: true
    }
  },
  mounted () {
  },
  methods: {
  }
}
</script>

<style scoped lang="less">
</style>

// src/components/boolean-edge-form/index.tsx
import type { BooleanEdge } from '@/graph/edges/boolean-edge';
import ProForm, { ProFormSwitch } from '@ant-design/pro-form';
import type { ProFormInstance } from '@ant-design/pro-form';
import type { FunctionComponent } from 'react';
import { useCallback } from 'react';
import { useRef } from 'react';
import { useEffect } from 'react';

interface BooleanEdgeFormProps {
  edge: BooleanEdge;
}

const BooleanEdgeForm: FunctionComponent<BooleanEdgeFormProps> = ({ edge }) => {
  const formRef = useRef<ProFormInstance>();

  const initForm = useCallback(() => {
    if (!formRef.current) {
      return;
    }
    formRef.current.setFieldsValue({
      value: edge.value,
    });
  }, [edge]);

  useEffect(() => {
    initForm();
  }, [initForm]);

  return (
    <ProForm
      formRef={formRef}
      onValuesChange={(values) => edge.changeValue(values.value)}
      submitter={false}
    >
      <ProFormSwitch
        name="value"
        label="条件是否成立"
        initialValue={edge.value}
      />
    </ProForm>
  );
};

export default BooleanEdgeForm;
