// src/components/condition-task-form/index.tsx
import ProForm, {
  ProFormDigit,
  ProFormSelect,
  ProFormDependency,
} from '@ant-design/pro-form';
import type { ProFormInstance } from '@ant-design/pro-form';
import type { FunctionComponent } from 'react';
import { useCallback } from 'react';
import { useRef } from 'react';
import { useEffect } from 'react';
import type {
  ConditionTaskShape,
  ConditionTaskShapeFormData,
} from '@/graph/shapes/condition-task';
import {
  CompareTypeOptions,
  ConditionValueType,
  ConditionValueTypeOptions,
} from './constant';

interface ConditionTaskFormProps {
  node: ConditionTaskShape;
}

const ConditionTaskForm: FunctionComponent<ConditionTaskFormProps> = ({
  node,
}) => {
  const formRef = useRef<ProFormInstance>();

  const initForm = useCallback(() => {
    if (!formRef.current) {
      return;
    }
    formRef.current.setFieldsValue(node.values);
  }, [node]);

  useEffect(() => {
    initForm();
  }, [initForm]);

  return (
    <ProForm<ConditionTaskShapeFormData>
      formRef={formRef}
      onValuesChange={(values) => {
        node.changeValues({
          ...formRef.current?.getFieldsValue(),
          ...values,
        });
      }}
      submitter={false}
    >
      <ProFormSelect
        name="valueType"
        label="条件类型"
        options={ConditionValueTypeOptions}
      />
      <ProFormDependency name={['valueType']}>
        {({ valueType }) => {
          if (valueType === ConditionValueType.AmountOfConsumption) {
            return <ProFormDigit label="条件值" name="value" min={0} />;
          }
          if (valueType === ConditionValueType.CountOfStores) {
            return <ProFormDigit label="条件值" name="value" min={0} />;
          }
          if (valueType === ConditionValueType.CountOfOrdersConsumed) {
            return <ProFormDigit label="条件值" name="value" min={0} />;
          }
          return null;
        }}
      </ProFormDependency>

      <ProFormSelect
        name="compareType"
        label="比较类型"
        options={CompareTypeOptions}
      />
    </ProForm>
  );
};

export default ConditionTaskForm;

// src/push-setting/graph/components/condition-task-form/index.vue
<template>
  <a-form :form="formRef" :label-col="{ span: 8 }" :wrapper-col="{ span: 16 }">
    <a-form-item label="比较类型">
      <a-select v-model="form.compareType" placeholder="请选择比较类型">
        <a-select-option :key="option.value" v-for="option of CompareTypeOptions" :value="option.value">{{ option.label }}</a-select-option>
      </a-select>
    </a-form-item>
    <a-form-item label="条件值">
      <a-input-number v-model="form.value" controls-position="right" :min="0" style="max-width: 166px;" />
    </a-form-item>
  </a-form>
</template>

<script>
import { ConditionTaskShape } from '../../shapes/condition-task'
import {
  CompareTypeOptions
} from './constant'

export default {
  name: 'ConditionTaskForm',
  props: {
    node: {
      type: ConditionTaskShape,
      default: null
    }
  },
  data () {
    return {
      formRef: this.$form.createForm(this),
      CompareTypeOptions,
      form: {
        ...this.node.values
      }
    }
  },
  watch: {
    node () {
      this.form = { ...this.node.values }
    },
    form: {
      handler () {
        this.node.changeValues(this.form)
      },
      deep: true
    }
  },
  mounted () {
  }
}
</script>

<style scoped lang="less">
</style>
